---
- hosts: all
  remote_user: ubuntu
  become: yes
  gather_facts: no      # NB: depends on Python2, which is not yet present
  pre_tasks:
    - name: 'Install python2'
      raw: sudo apt-get -y install python-simplejson
    - name: 'gather facts'
      action: setup
  tasks:
    - name: 'Update repositories cache'
      apt:
        update_cache: yes
  roles:
    - docker
    - books-service
